---
title: "User 83882"
author: "Ben Peloquin"
date: "April 13, 2016"
output:
  html_document:
    toc: true
---

```{r}
rm(list = ls())
setwd("~/Desktop/Spring2016/CS224U/rateBeerLingRel")
```

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(stringr)
```

# Read in single csv
```{r}
d <- read.csv("83882.csv", )
# str(d)
# View(d)
```

# Prelim explore

## Overall score
```{r}
ggplot(d, aes(overallScore)) +
  geom_bar()
```

## Average score
```{r}
ggplot(d, aes(avgScore)) +
  geom_bar()
```


## Palatte score
```{r}
ggplot(d, aes(palateScore)) +
  geom_bar()
```

## Aroma score
```{r}
ggplot(d, aes(aromaScore)) +
  geom_bar()
```

## Taste score
```{r}
ggplot(d, aes(tasteScore)) +
  geom_bar()
```

## Appearance score
```{r}
ggplot(d, aes(appearanceScore)) +
  geom_bar()
```

## Review Length
```{r}
d$reviewLength <- sapply(d$reviewBlob, str_length)
ggplot(d, aes(reviewLength)) +
  geom_density()
```

## Summary Stats
```{r}
d %>%
  select(overallScore, avgScore, palateScore, aromaScore, tasteScore, appearanceScore, reviewLength, userID) %>%
  gather(scoreType, score, -userID) %>%
  group_by(scoreType) %>%
  summarise(mu = mean(score),
            sd = sd(score))
```


